-- MySQL Script generated by MySQL Workbench
-- Sat Oct  8 23:08:34 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema rick_and_morty
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema rick_and_morty
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `rick_and_morty` DEFAULT CHARACTER SET utf8 ;
USE `rick_and_morty` ;

-- -----------------------------------------------------
-- Table `rick_and_morty`.`episodes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rick_and_morty`.`episodes` ;

CREATE TABLE IF NOT EXISTS `rick_and_morty`.`episodes` (
  `id_episodio` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `temporada_episodio` VARCHAR(45) NULL,
  `fecha_estreno` VARCHAR(45) NULL,
  PRIMARY KEY (`id_episodio`),
  UNIQUE INDEX `idepisodio_UNIQUE` (`id_episodio` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rick_and_morty`.`ubicacion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rick_and_morty`.`ubicacion` ;

CREATE TABLE IF NOT EXISTS `rick_and_morty`.`ubicacion` (
  `id_ubicacion` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `dimension` VARCHAR(45) NULL,
  `tipo` VARCHAR(45) NULL,
  `ubicacioncol` VARCHAR(45) NULL,
  PRIMARY KEY (`id_ubicacion`),
  UNIQUE INDEX `id_ubicacion_UNIQUE` (`id_ubicacion` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rick_and_morty`.`personajes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rick_and_morty`.`personajes` ;

CREATE TABLE IF NOT EXISTS `rick_and_morty`.`personajes` (
  `id_personajes` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `especie` VARCHAR(45) NOT NULL,
  `genero` VARCHAR(45) NULL,
  `id_ubicacion` INT NOT NULL,
  PRIMARY KEY (`id_personajes`),
  UNIQUE INDEX `idpersonajes_UNIQUE` (`id_personajes` ASC) VISIBLE,
  INDEX `fk_personajes_ubicacion1_idx` (`id_ubicacion` ASC) VISIBLE,
  CONSTRAINT `fk_personajes_ubicacion1`
    FOREIGN KEY (`id_ubicacion`)
    REFERENCES `rick_and_morty`.`ubicacion` (`id_ubicacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rick_and_morty`.`episodios_personajes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rick_and_morty`.`episodios_personajes` ;

CREATE TABLE IF NOT EXISTS `rick_and_morty`.`episodios_personajes` (
  `id_episodios` INT NULL,
  `id_personajes` INT NULL,
  INDEX `fk_episodios_personajes_personajes1_idx` (`id_personajes` ASC) VISIBLE,
  CONSTRAINT `fk_episodios_personajes_episodes`
    FOREIGN KEY (`id_episodios`)
    REFERENCES `rick_and_morty`.`episodes` (`id_episodio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_episodios_personajes_personajes1`
    FOREIGN KEY (`id_personajes`)
    REFERENCES `rick_and_morty`.`personajes` (`id_personajes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
